import type { SyncNode } from '@/model/security.types';

const APP = 'security-core';

export const NAV_REGISTRY: SyncNode[] = [
  // ── Entities ──────────────────────────────────────────────────────────────
  {
    menuId: 'entities',
    appName: APP,
    menuName: 'entities',
    label: 'Entities',
    ordering: 10,
  },
  {
    menuId: 'entities.organizations',
    appName: APP,
    menuName: 'entities.organizations',
    label: 'Organizations',
    parentMenuId: 'entities',
    route: '/organizations',
    icon: 'Building2',
    ordering: 10,
  },
  {
    menuId: 'entities.employees',
    appName: APP,
    menuName: 'entities.employees',
    label: 'Employees',
    parentMenuId: 'entities',
    route: '/employees',
    icon: 'Users',
    ordering: 20,
  },

  // ── Master Data ────────────────────────────────────────────────────────────
  {
    menuId: 'master-data',
    appName: APP,
    menuName: 'master-data',
    label: 'Master Data',
    ordering: 20,
  },
  {
    menuId: 'master-data.departments',
    appName: APP,
    menuName: 'master-data.departments',
    label: 'Departments',
    parentMenuId: 'master-data',
    route: '/departments',
    icon: 'Users',
    ordering: 10,
  },

  // ── Reports ────────────────────────────────────────────────────────────────
  {
    menuId: 'reports',
    appName: APP,
    menuName: 'reports',
    label: 'Reports',
    ordering: 30,
  },
  {
    menuId: 'reports.report01',
    appName: APP,
    menuName: 'reports.report01',
    label: 'Report 01',
    parentMenuId: 'reports',
    route: '/reports/report01',
    icon: 'FileText',
    ordering: 10,
  },
  {
    menuId: 'reports.report01.detail',
    appName: APP,
    menuName: 'reports.report01.detail',
    label: 'Detail',
    parentMenuId: 'reports.report01',
    route: '/reports/report01/detail',
    icon: 'FileText',
    ordering: 10,
  },
  {
    menuId: 'reports.report02',
    appName: APP,
    menuName: 'reports.report02',
    label: 'Report 02',
    parentMenuId: 'reports',
    route: '/reports/report02',
    icon: 'FileText',
    ordering: 20,
  },
  {
    menuId: 'reports.report02.detail',
    appName: APP,
    menuName: 'reports.report02.detail',
    label: 'Detail',
    parentMenuId: 'reports.report02',
    route: '/reports/report02/detail',
    icon: 'FileText',
    ordering: 10,
  },

  // ── Administration ─────────────────────────────────────────────────────────
  {
    menuId: 'admin',
    appName: APP,
    menuName: 'admin',
    label: 'Administration',
    ordering: 40,
  },
  {
    menuId: 'admin.users',
    appName: APP,
    menuName: 'admin.users',
    label: 'User Management',
    parentMenuId: 'admin',
    route: '/admin/users',
    icon: 'Users',
    ordering: 10,
  },
  {
    menuId: 'admin.security',
    appName: APP,
    menuName: 'admin.security',
    label: 'Security',
    parentMenuId: 'admin',
    route: '/admin/security',
    icon: 'Shield',
    ordering: 20,
  },
  {
    menuId: 'admin.security.roles',
    appName: APP,
    menuName: 'admin.security.roles',
    label: 'Roles',
    parentMenuId: 'admin.security',
    route: '/admin/security/roles',
    icon: 'Shield',
    ordering: 10,
  },
  {
    menuId: 'admin.security.menu-definitions',
    appName: APP,
    menuName: 'admin.security.menu-definitions',
    label: 'Menu Definitions',
    parentMenuId: 'admin.security',
    route: '/admin/security/menu-definitions',
    icon: 'Menu',
    ordering: 20,
  },
];
